# Christian heresy
name = "Gnosticism"
adj = "Gnostic"
pedia = """Gnosticism is a collection of religious ideas and systems that coalesced in the late 1st century AD among Jewish and early Christian sects. These various groups emphasized personal spiritual knowledge (gnosis) above the proto-orthodox teachings, traditions, and authority of religious institutions."""
