# Amis Folk Religion
name = "Kawaskawas"
adj = "Kawaskawas"
pedia = """Kawaskawas refers to a set of spiritual beliefs, such as a religion. Kawas refers to an Amis supernatural entity. Though the Amis have converted to Christianity, their spiritual beliefs and Christianity have syncretized and the term kawas is still used. Kawas are divided into 6 groups: gods, ancestors, souls of living, spirits of living things, spirits of lifeless objects, and ghosts. Bamboo oracle specialists were among communicators. Lisin, or ceremony, was the preferred method to cope with kawas."""
