# Mordvin religion
name = "Mastorava"
adj = "Mastorava"
pedia = """Mordvin Neopaganism, or the Mordvin native religion or Erzyan native religion, is the modern revival of the ethnic religion of the Mordvins (Erzya and Moksha), peoples of Volga Finnic ethnic stock dwelling in the republic of Mordovia within Russia, or in bordering lands of Russia. The religion is often called Mastorava (Mordvin for: "Mother Earth"), from the homonymous epic poem or the mother goddess of the Mordvin pantheon. The name of the originating god according to the Mordvin tradition is Ineshkipaz."""
