# Christian heresy
name = "Waldensianism"
pedia = """The Waldensians are adherents of a church tradition that began as an ascetic movement within Western Christianity before the Reformation. Originally known as the "Poor Men of Lyon" in the late twelfth century, the movement spread to the Cottian Alps in what are today France and Italy. The founding of the Waldensians is attributed to Peter Waldo, a wealthy merchant who gave away his property around 1173, preaching apostolic poverty as the way to perfection.

In the 16th century, the Waldensians were absorbed into the Protestant movement, under the influence of early Swiss reformer Heinrich Bullinger. They are members of the Community of Protestant Churches in Europe and its affiliates worldwide. They were nearly annihilated in the 17th century.

The main denomination within the movement was the Waldensian Evangelical Church, the original church in Italy."""
